### ISSUE TITLE
Add Workflow KPI extension

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#108]
**What would you like to be added**:

This request is to add Key Performance Indicators (KPI)  spec extension.

**Why is this needed**:
- How can we monitor which workflow or specific states were completed in time and which did not? 
- How can we monitor if a specific function execution (service call)  was completed in time? How can we monitor if its execution was within the range of expected cost?

KPI is very useful to have for runtime workflow analysis tools.

**Comment by manuelstein** [comment]
Is this more than just tracing? (collect timing and resource usage of each function, step, workflow execution)
- Analysis tools could be attached to the platform performing the execution. So, this could be requirements, a common information model or an API for a platform.
- Restricting resource usage to control the cost of an execution could be expressed by quota that are part of the invocation (e.g. in a specific workflow, the function should not be able to use more than 128MB memory), but such an interface is currently not part of any remote function invocation, and not with event-driven invocations
- To use such data in the workflow (e.g. taking a different branch when the result produced is larger than 20MB) or when the previous execution took longer than 1h would yet be a different usage performance data 

So, I believe what we're looking for here are common identifiers in OpenTracing that would mark the KPI and a requirement for the execution (workflow engine, function) to provide these tracing data, so that users of Serverless Workflows have a common way of analysing workflows and are not dependent on the proprietary log/monitoring interfaces. Is that the idea?

**Comment by ricardozanini** [comment]
Not sure with we should mix non-functional requirements such KPIs to the Workflow definition. Maybe a new schema that takes a workflow as a reference that can be deployed in the platform and turn the execution into KPI data?

**Comment by tsurdilo** [comment]
@ricardozanini it will be implemented as a workflow extension, so not part of the workflow definition (updated the issue).

@manuelstein: its not really tracing, for that we should have a dedicated "tracing" extension where i agree with can follow OpenTracing. KPI is a set of "expected" values such as cost, max times, error count, event count, error count etc

**Comment by tsurdilo** [comment]
PR: https://github.com/serverlessworkflow/specification/pull/109
