### ISSUE TITLE
Should the order of conditions in a Switch State be honored by implementations?

### ISSUE THREAD

**Issue by LCaparelli** [serverlessworkflow/specification#156]
**What is the question**:
Are implementations expected to honor the order of Switch State conditions? Seems logical, but it's not explicitly stated, so I thought it would be worth asking.

In a switch with 2 conditions (A and B), it's possible that both condition A and B are true, so order matters as either A or B are eligible for execution and could produce different results depending on which gets ran.

I believe this is important not only to data-based conditions, but to event-based conditions as well: it's possible that event A and B have already happened or arrive simultaneously when this switch state is reached and the order on which they are consumed matters.

**Comment by tsurdilo** [comment]
@LCaparelli good questions. i am planning to add an optional "priority" integer type param to each condition which would solve the issue you are addressing. its been on my radar for a while now just havent been able yet. expect a pr on this soon :) thank you

**Comment by LCaparelli** [comment]
Great! Working with priorities is a nice generalization, +1

**Comment by LCaparelli** [comment]
As discussed in yesterday's meeting I'll send in a PR explicitly stating that the order on which the conditions are defined must be honored. It was decided then that we'd go with this approach instead of working with priorities.

The [standard ECMA-404](https://www.ecma-international.org/publications/standards/Ecma-404.htm) guarantees ordering of arrays in JSON.

> JSON also provides support for ordered lists of values. All programming languages will have some feature for representing  such  lists,  which  can  go  by  names  like array, vector,  or list.

I was also able to find this guarantee in [YAML specification](https://yaml.org/spec/1.1/current.html#sequence/information%20model):

> The content of a sequence node is an ordered series of zero or more nodes. In particular, a sequence may contain the same node more than once or it could even contain itself (directly or indirectly).

So we should be good with this approach.

**Comment by tsurdilo** [comment]
@LCaparelli after thinking about this some more -- yes I agree that this should be the "default" behavior and I would define it in the documentation as such. 
However, in order to allow existing business automation runtimes which might not represent this as an ordered list (and do not or cannot change) I do believe that adding an optional interger-type "priority" parameter should be added.

So I would say default the order is defined by the order in the array in the markup (if no priority is explicitly set), and in addition we do allow for setting priority via parameters with the note that if priority param is set it should have precedence over the default behaviour (orde).

WDYT?

**Comment by LCaparelli** [comment]
That seems reasonable to me @tsurdilo. 

One question though: if a priority is specified for one condition, then the user **must** specify it for all conditions, right? Otherwise it's still ambiguous, I think.

**Comment by tsurdilo** [comment]
@LCaparelli yes that would be correct
