### ISSUE TITLE
ForEach State 、Parallel State: Branch  use workflowId Question

### ISSUE THREAD

**Issue by sky132333** [serverlessworkflow/specification#171]
**What is the question**:
In ForEach State 、Parallel State: Branch  use sub-workflow id . How to specify whether to wait for the sub-workflow to complete ? Why does subflow state have waitforcompletion, but foreach state and parallel state: branch does not?

**Comment by tsurdilo** [comment]
@sky132333 
Parallel state defines branches. It has the completionType parameter which controls branch execution.
ForEach state as defined also in spec is used to execute a defined actions, or execute a sub-workflow for each element of a data array" Key word here being "for each element", which means completion is required in order to fulfill the definition of this state.

Hope this helps

**Comment by sky132333** [comment]
Thank for answer.
