### ISSUE TITLE
State data clarification

### ISSUE THREAD

**Issue by jensg-st** [serverlessworkflow/specification#214]
**What would you like to be added**:

According to the [specification](https://github.com/serverlessworkflow/specification/blob/master/specification.md#Workflow-Data-Input): "The initial data input into a workflow instance must be a valid JSON object. If no input is provided the default data input is the empty object".

The specification should clarify whether the every state's data should be a valid JSON object at all times.

On one hand it seems like this is the intention, considering how the Inject State cannot work unless this is true. It is also impossible to merge event data or subflow results into the state unless this is the case. As it stands, getting the state data into something that's not a valid JSON object is unrecoverable and renders many operations impossible.

On the other hand, the specification explicitly provides [examples](https://github.com/serverlessworkflow/specification/blob/master/specification.md#Workflow-Data-Expressions) where JSONPath filters turn the output of a state into something that is not a valid JSON Object. In the first example, the state data is converted from an object into an array. 

**Why is this needed**:

As a reader of the spec, it is unclear to me what types of state data are possible. Allowing anything can allow for more powerful output, but can also render a great deal of functionality inoperable. Because there's no way right now to recover from a non JSON Object state there appears to be a gap in the specification that could use clarification. 

If the state data should always be a valid JSON Object that would resolve all problems nicely, at the cost of some small amount of functionality and some incorrect examples in the spec. 

If the state data doesn't have to be a valid JSON Object, the specification should be expanded to either:

a) enforce that the only time it can be violated is in the output filter for an end state, or 

b) include a way to recover from such a state.

**Comment by tsurdilo** [comment]
@jensg-st good catch - all workflow data (workflow and state input/output) must be valid JSON. Will go through the examples in spec doc and correct this asap.

**Comment by tsurdilo** [comment]
@jensg-st after looking at the example you mentioned in the post, it does show a valid json structure.

```json
[
   {
      "type" : "iPhone",
      "number" : "0123-4567-8888"
   },
   {
      "type" : "home",
      "number" : "0123-4567-8910"
   }
]
```

is valid json. Could you elaborate on why you think this is an issue?

**Comment by tsurdilo** [comment]
@jensg-st https://github.com/serverlessworkflow/specification/pull/217 . please review when you have time

**Comment by alankm** [comment]
Just throwing in my two-cents: you could make that change if you like supporting JSON arrays. But then what's the spec's answer to this?

> If the state data doesn't have to be a valid JSON Object, the specification should be expanded to either:
> 
> a) enforce that the only time it can be violated is in the output filter for an end state, or
> 
> b) include a way to recover from such a state.

**Comment by tsurdilo** [comment]
@alankm not sure what the issue is. 
with workflow data having to be valid json: 
a) the answer would be that it cannot be "violated"
b) the answer would be that runtime has to enforce workflow input is valid json, it has to enforce that it keeps being valid json during workflow execution and it has to enforce that workflow output is again valid json

hope this helps

**Comment by alankm** [comment]
An array such as in the documentation example is valid JSON, but because it's not a JSON object it is unclear (perhaps impossible) how to perform Inject States on it and/or merge data into it after receiving an event or running a function. 

For example, if you have the following state:

```json
{
  "input": "hello"
}
```

And run a function that returns this json:

```json
{
  "output": "goodbye"
}
```

It's easy to understand how to merge that function output back into the state. It should become this:

```json
{
  "input": "hello",
  "output": "goodbye"
}
```

Now consider what happens if your state is a JSON array. You begin with this state:

```json
[
  {
    "input": "hello"
  },
  {
    "input": "aloha"
  }
]
```

How can I merge my function output into this? Do I append it to the end of the array? Do I merge it into each array element?

"Valid JSON" also includes primitives like `true` or `"hello"`. How can I merge my function output into that?

These are the questions the spec needs to answer.

**Comment by tsurdilo** [comment]
@alankm I believe that we cannot via specification alone prevent possible merging errors from happening. It is often during testing (workflow exec) that users can find out these types of issues. 

That being said,  if I'm not mistaken your example can only occur in the case where the workflow data input is an array. Otherwise if the workflow data input is json object, its type would be maintained throughout workflow execution.

So I think we have couple choices,
1) we leave the workflow data input clause (being a valid json object) as is currently, and update the example you mentioned.
2) we apply the updates in linked pr

for both cases probably should be worth adding to spec doc that merging errors during workflow execution should be able to be handled via states onErrors definitions. WDYT?

**Comment by alankm** [comment]
> That being said, if I'm not mistaken your example can only occur in the case where the workflow data input is an array. Otherwise if the workflow data input is json object, its type would be maintained throughout workflow execution.

Just to demonstrate that this isn't true using the specification example:

Workflow input:

```json
{
  "firstName": "John",
  "lastName" : "Doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "Naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

Workflow:

```yaml
id: helloworld
name: "Hello, World!"
description: "Demo #01: A simple hello world."
states:
- name: First
  type: delay
  timeDelay: 1M
  start:
    kind: default
  transition:
    nextState: Second
  stateDataFilter:
    dataOutputPath: "{{ $.phoneNumbers }}"
- name: Second
  type: inject
  data:
    greeting: hello 
  end:
    kind: default
```

The first state in this workflow is effectively identical to the example in the specification, and it transforms the state data from an object to an array. This breaks the second state.

Personally, I think it'd be simpler and cleaner to enforce that it is always an **object**. Users can nest their arrays and primitives inside.

**Comment by tsurdilo** [comment]
@alankm ok, idk what i was thinking before....
Results of the jsonpath expression in dataOutputPath is always going to return an array so enforcing state to return json object is fine but we need to then make sure that users can define the element name for expression results.
For example:

```json
"stateDataFilter": {
     "dataOutputPath":  "{{ $.phoneNumbers[0] }}",
     "as": "iPhoneNumber"
}
```

**Comment by alankm** [comment]
One possible solution is to replace JSONPath with jq :)

But there are others, like your suggestion.

**Comment by tsurdilo** [comment]
@alankm hehe yes, "{iPhoneNumber: .phoneNumbers[0]}" does looks much easier.
