### ISSUE TITLE
Question: can the semantics of EventState be simplified while still achieving its design goals?

### ISSUE THREAD

**Issue by jplane** [serverlessworkflow/specification#257]
I think I understand the goal of EventState as a means to rendezvous events and trigger corresponding actions, specifically:

- Exclusive = true means the arrival of one of a set of defined events triggers the associated actions
- Exclusive = false means the arrival of all defined events triggers the associated actions

The issue I see with EventState is the OnEvents attribute, which effectively creates an array of "defined event array + associated action array" (so, a nested array structure). Its not clear to me what benefit this brings to the above design goals for EventState (assuming those are in fact the goals :-) ).

The presence of OnEvents makes it seem like EventState should define groups of "awaited events" (each group can have 1+ await events) and apply the top-level exclusivity attribute within each group... which makes me wonder why not just push Exclusive down to the group level instead of keeping it at the top level.

Or, if Exclusive should apply to the overall state execution and govern when the state is done ("state is done when one element in OnEvents is triggered, or all are triggered") then I'm still confused because each individual element inside OnEvents can itself contain multiple awaited events, and its not clear whether implementations should wait for one or all of those.

Basically, I'm not sure how to interpret Exclusive and OnEvents and relate those to overall completion of EventState.

Consider this example:

```json

{
"name": "MonitorVitals",
"type": "event",
"start": true,
"exclusive": true,
"onEvents": [{
        "eventRefs": ["HighBodyTemperature", "ManualOverrideSendTylenol"],
        "actions": [{
            "functionRef": {
                "refName": "sendTylenolOrder",
                "parameters": {
                    "patientid": "{{ $.patientId }}"
                }
            }
        }]
    },
    {
        "eventRefs": ["HighBloodPressure", "ManualOverrideCallNurse"],
        "actions": [{
            "functionRef": {
                "refName": "callNurse",
                "parameters": {
                    "patientid": "{{ $.patientId }}"
                }
            }
        }]
    },
    {
        "eventRefs": ["HighRespirationRate", "ManualOverrideCallPulmonologist"],
        "actions": [{
            "functionRef": {
                "refName": "callPulmonologist",
                "parameters": {
                    "patientid": "{{ $.patientId }}"
                }
            }
        }]
    }
],
"end": {
    "terminate": true
}
}

```

Given that Exclusive = true, what happens if "HighBloodPressure" event is consumed? Invoke "callNurse" action and then the state completes? Or something else?

If Exclusive = false, what combination of events is required to complete the state? From the spec I'm not sure... seems like it could be HighBloodPressure + ManualOverrideCallNurse, or HighBodyTemp + HighBloodPressure + HighRespirationRate, or something else entirely...?

Is there a way to simplify this a bit and still achieve the original design goal of "catch one or more events and trigger one or more actions"? Could EventState get rid of OnEvents and simply map an EventRef array to Actions? Or does this prevent modeling certain useful scenarios?

**Comment by tsurdilo** [comment]
@jplane 

**Given that Exclusive = true, what happens if "HighBloodPressure" event is consumed? Invoke "callNurse" action and then the state completes? Or something else?**
Yes, in this case, if exclusive is true, either occurrence of "HighBloodPressure" or  "ManualOverrideCallNurse" would invoke the associated actions (in this case "callNurse"). 

**If Exclusive = false, what combination of events is required to complete the state? From the spec I'm not sure... seems like it could be HighBloodPressure + ManualOverrideCallNurse, or HighBodyTemp + HighBloodPressure + HighRespirationRate, or something else entirely...?**
In your example its 3 possible choices:
1) "HighBodyTemperature" + "ManualOverrideSendTylenol"
2) "HighBloodPressure" + "ManualOverrideCallNurse"
3) "HighRespirationRate" + "ManualOverrideCallPulmonologist"


You can think onEvents array elements as individual starting states, each one specifying a certain set of event(s) which can trigger the associated actions (of course depending exclusive param value) after those particular actions are completed the state then can either transition or end workflow execution (if end:true). 

I do think that we could define "exclusive" per onEvents element...really good idea!
Let's define some example of that and see how it looks. Thank you!

**Comment by tsurdilo** [comment]
@jplane I think simplifications to event state are also good to look at. we had some discussions around it here as well : https://github.com/serverlessworkflow/specification/issues/228

**Comment by tsurdilo** [comment]
Step 1 event state update: make onevents actions property not required: https://github.com/serverlessworkflow/specification/pull/269
