### ISSUE TITLE
External schema are not valid on their own.

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/specification#407]
**What would you like to be added**:
"Strictly" valid JSON Schema for externally referenced schemas without "custom" properties?

**Why is this needed**:
The [schemas](https://github.com/serverlessworkflow/specification/tree/main/schema) are divided in multiple files, there is the main entry point [workflow.json](https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json) and external definitions. The [reason](https://github.com/serverlessworkflow/sdk-typescript/issues/73#issuecomment-830070037) for having those definitions externally instead of inside the `definitions` property of `workflow.json` is to let the user validate pieces of the schema independently. Aside from the the arguably questionnable choice of having those definitions external (how is using `secrets.json` easier than `workflow.json#/definitions/secrets` or why choose to make `secrets` external but not `states` for instance), those external definitions are not valid on their own (see json schema conversations [here](https://json-schema.slack.com/archives/C5CF75URH/p1619795358400800) and [here](https://json-schema.slack.com/archives/C5CF75URH/p1619796577402700)). From `workflow.json`, a reference to `secrets.json#/secrets` is working as it is a direct pointer to a property in the secrets definition file. But loading `secrets.json` on its own is quite useless as the `secrets` property at the root level is not a valid JSON Schema property.

**Comment by tsurdilo** [comment]
The workflow definition can include a number of reusable pieces, namely function, events, retries, secrets, and soon auth definitions. Those can be reused across multiple workflow definitions.
We apply reusability of control flow logic via SubFlows and thus do not have a specific schema for the states. 
The only "outlier" is the metadata definition which we externalized because it is used in so many places in the workflow schema that it makes sense to have it separate so changes to it do not have to be done in a million places.

The individual schemas should be self-validating, for example secrets.json:

<img width="1546" alt="Screen Shot 2021-06-16 at 2 22 01 PM" src="https://user-images.githubusercontent.com/119422/122272398-83744a80-ceae-11eb-84cf-cd2549ec3f4d.png">

Hope this helps.

**Comment by tsurdilo** [comment]
> But loading secrets.json on its own is quite useless as the secrets property at the root level is not a valid JSON Schema property.

Thats not the point of the secrets schema. It is to provide the ability for users/tools to validate an external secrets def as well as the one defined inside the workflow definition. 
That way if user says he wants to use "mysecrets.json" in the workflow def runtimes can validate it on its own and report errors if that validation fails before user should deploy the workflow def

**Comment by JBBianchi** [comment]
Ok, I think I understand, thanks.
