### ISSUE TITLE
Make workflow "id", "key" parameters not required

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#463]
**What would you like to be added**:
Make id , key params not required
**Why is this needed**:
if one is not provided, runtime can generate unique

**Comment by manick02** [comment]
I will take a look at this as well. This seems similar to #464

**Comment by tsurdilo** [comment]
nice. yeah update the schema and the required field in table and then we can figure out the text in spec doc that needs updates. thanks

**Comment by cdavernas** [comment]
IMHO, turning all those properties into optionals might bring in some quality of life issues for users. As a matter of fact, if a user deploys a workflow and overlooks the returned ID or key, he's left with no ubiquitous way to find that workflow amongst potentially hundreds of definitions. I believe those properties should be mutually exclusive, leaving the user with a choice concerning identification. Plus, versioning, which's in my opinion absolutely critical, is left with no purpose in case of lack of explicit identification (or auto-generated one): if I upload one revision of a workflow, with auto-id and auto-version, then publish another revision of it, runtimes will have 2 choices: considering them both as separate, unique workflows (making version useless) or having some kind of parsing mechanism (shaky at best) to determine that they are 2 revisions of a single definition.

**Comment by tsurdilo** [comment]
@cdavernas are we concerned finding workflow definitions or workflow instances?
As far as definitions goes, those are user-defined.
User would need some id which is almost always runtime-specific. This they should get from the runtime, on deployment/execution time. 

Typically the id alone is not enough to identify a workflow instance/execution. You also need some instance id which in combination to the workflow identification is unique. In distributed systems sometimes you need even a third param like a "namespace" on where the workflow instance is actually running (as can run on multiple at times).

WDYT?

**Comment by tsurdilo** [comment]
@cdavernas side-tracking this discussion, we should probably add a "namespace" param to our dsl. 
Currently no matter the runtime, the DSL cannot specify that one workflow state should run on a different pod for example than another. It's assumed that either they all run on the same pod or its up to the magic of the runtime to figure that out.

There are however many use cases where you want certain work to be performed on specific pods. For example consider file uploading. Once a file for a specific customer has been uploaded to pod A, then all subsequent file uploads for that customer should be also done on the same pod. How can we define that currently in DSL? I don't think there is a way.

**Comment by ricardozanini** [comment]
> Currently no matter the runtime, the DSL cannot specify that one workflow state should run on a different pod for example than another. It's assumed that either they all run on the same pod or its up to the magic of the runtime to figure that out.

@tsurdilo, I think we shouldn't have this defined in the DSL. Again, it's a matter of infrastructure, which implementations should manage by themselves.

Kubernetes, for example, has the ability to control objects by labels and annotations. Implementations should expose such information relying on the platform it's running. If the SW would have a Kubernetes CRD representation, one can leverage these attributes from the platform. No need to duplicate here. We should stick with the domain model only, IMO.

**Comment by tsurdilo** [comment]
@ricardozanini 
I think thats fair, but it is from the point of view of a "closed system", meaning user does not control the deployment infra. 
In those types of systems requirements like defining that workflow states A, B, C should all run in the same location and D, E on another (these are real business requirements btw) cannot even be considered and many people fall to not using workflows for those situations at all.

The main use case for this is file uploading/downloading. We cannot assure currently that user requirement of all associated file uploads/downloads happen on the same "instance".

Another use cases that is very important is for users to be able to have multiple clusters/pods/infras, each provisioned differently. They want then a workflow state that processes 1TB of data to run on cluster A which is provisioned for high IO operations, and rest of states on some other cluster.

I used the term "pod" in last message but this is not specific for kubernetes at all. It could as well be cluster or substitute any other word that is tied to a virtual machine.

**Comment by cdavernas** [comment]
@tsurdilo 
> @cdavernas are we concerned finding workflow definitions or workflow instances?
Well, in my use cases, I am indeed concerned with finding workflow definitions and their associated instances. This is for tracking, tracing, management, log aggregation and metrics.

Furthermore, as I said in my comment, I think it's important we think about the versioning aspect. If the `id` is auto-generated by the runtime, there is no need for versioning, as any definition added in the future will be considered a new one, instead of a revision, if the user has not manually retrieved it (how so, if it's just UUIDs? Creation timestamp? Doesn't feel nice to me) and input it in its revision? The way I'm using my runtime implementation allows me - because any kind of user-inputed identifier is required for now, should it be key, name, id - is to auto-increase the version of a definition that has the same name than an existing one, thus making sure the user does not inadvertently override an old, still running version of it, and all the data associated to it. With that system, this is gone. As are fancy dashboard (of the like of Camunda-Operate) allowing the user to track, manage, manually compensate, etc., workflows in a human-readable fashion (as opposed to just facing UUIDs).

> As far as definitions goes, those are user-defined.
So far, they are required to be set by users. The change you suggest, however, is to make it optional, which WILL result in users inadvertently creating workflows without setting any expected identifier and facing the difficulty of finding it easily afterwards, even if only to delete. IMHO, we should enforce AT LEAST ONE user-defined property for identification purpose. IMHO, the `name` property was perfect to achieve that. I'm still fly with `key` or `id` though. As long as at least one is required. Even for things such as Custom Resource Definitions, K8s enforces setting at least the `name` (as well as a couple other properties). And that is for quality of use purpose only.

WDYT?

**Comment by cdavernas** [comment]
@tsurdilo Regarding your idea on pod-related config and such, though I find it interesting, I tend to agree with @ricardozanini, as often. 

In my personal opinion, deployment related information is out of Serverless Workflow scope, as it is a runtime/infrastructure concern. It's purely related to the control plane, which lies way beyond the boundaries of the spec as I see it.
At best, we could cook up some kind of orchestration-related extension and its related documentation, and runtimes have the choice to support it or not (which Synapse will, if that's the case).

WDYT?

**Comment by ricardozanini** [comment]
@tsurdilo I think the research/study @cdavernas and I are doing about representing the SW on "containers orchestration platforms" would answer many of these questions you brought in your previous comment. 

They are super valid, and I think we need to bring them to the table. Perhaps opening a new doc about how the spec is supposed to be represented in such environments. Not written in stone, more like suggestions for implementations. Things we are learning with our own implementations and integration with serverless platforms.

**Comment by tsurdilo** [comment]
@manick02 seems after these discussions we want to hold off on this issue for now, sorry. 
We can work on the other open good first issues if you are up for it :) . Will try to open some more this week as well.

@cdavernas @ricardozanini the dsl does not have to contain some deployment related information as we always abstract that. The point I was trying to make  is that we cannot currently describe some user business requirements and was trying to bring that up for discussions.

**Comment by manick02** [comment]
@tsurdilo thanks, I will pick up other two :)
