### ISSUE TITLE
Clearly define the use for top-level "key" property

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/specification#584]
We added the top workflow-level "key" property for a specific use case where the workflow id might get "generated" by some CMS or something.
Because of this we kinda misuse it as something that identifies uniqueness of the workflow definition. In reality it's use is more on the workflow instance uniqueness level. 

Request here to either remove it or clearly state what its use is/should be.

**Comment by mswiderski** [comment]
I agree that this is currently confusing in the spec but I'd like to keep it but repurpose it instead.

So `key` should not reference definition but reference instance of the workflow. So the `key` attribute would be an expression that could be evaluated upon start of the workflow based on the input of the workflow instance to assign alternative id e.g. order number, employee id etc.

That way we have `id` as the main identifier of the workflow definition and each instance of the definition could use `key` expression to assign domain specific identifier of the instance instead of or next to the one that is generated by runtime.

**Comment by tsurdilo** [comment]
hows should that work when data for key comes from one or more events handled by starting event state? whats proposed  rule when you have both data input and are event-teiggered? is key immutable?

**Comment by mswiderski** [comment]
key will be set only once upon instance creation and it is immutable, same as id is. It has exactly the same behavior as id - is set only once when new instance is created.

**Comment by tsurdilo** [comment]
you mean the run/exec id, not the wf def id right? 
if so its pretty hard imo to define when its set without going into runtime details as in when wf instance is created. wdyt

**Comment by tsurdilo** [comment]
without looking at runtime specific instance creation could it be set on starting wf state (with special instructions for event state)? if so can state handle expression error?

**Comment by mswiderski** [comment]
I don't think there is a need to go into specifics of runtime and instance creation. I think it is enough to describe that it will be set when instance is created and that part can be specific to runtime but anyway each instance needs to be started at some point. Either by incoming events, manual trigger and so on.

**Comment by mswiderski** [comment]
`key` expression failures should be ignored and simply key is not set when expression fails.

**Comment by cdavernas** [comment]
Completely agree with @mswiderski ! Implemented it already and it just rules! Great, great idea, especially for user Quality Of Life
