### ISSUE TITLE
what's the difference between  ${ { } }and ${} ?

### ISSUE THREAD

**Issue by Yan1025** [serverlessworkflow/specification#761]
As the title, when i using jq1.6，i found there are two types of expression in your official documents. So, what's the difference?

**Comment by ricardozanini** [comment]
Hi! Can you bring the context in the docs where you've found the `${ {} }`? So we can clarify.

The `${}` denotes a jq expression string. Since most of our handlers are strings, we need a safe way for the engines to parse the string correctly into a jq expression.

Depending on the context, the `${ {} }` might denote the ObjectConstruction formula on jq side. Take a look: https://stedolan.github.io/jq/manual/#ObjectConstruction:{}

So that the outcome of such expression is a new JSON object to the next action/state/handler within the workflow.

Cheers!
